import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Test Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="../../public/assets/images/favicon-32x32.png" />
      </head>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
